### This notebook will introduce you to understand the elements within an energy balance model of the Earth system and apply a simple approach to quantify how changes in absorbed shortwave radiation (ASR), atmospheric emissivity, and albedo impact Earth’s surface temperature.

 __Author__: Sara Grisales-Vargas. For any questions regarding the contents of this notebook please contact sara.grisales.vargas@temple.edu.deriv
ed above

s n Solar
n Volcanic

### Datasets used to develop the energy balance model:

**Simulated change in global average surface air temperature** from NASA GISS ModelE2 developed as NASA’s Goddard Institute for Space Studies (*NASA_GISS_Response_To_Forcings.csv*)
 *  Units: Kelvin

**Observed change in global average surface air temperature** for comparison to 
model result (*Observed_Temps.csv*)
 *  Units: Kelvin

**Annual-mean Total Solar Irradiance (TSI) reconstruction** based on the 
“Community-Consensus TSI Composite” (Dudok de Wit et al., GRL, 2017) and 
SATIRE-T model (Wu et al,
A&A, 2018). Computed by Greg Kopp using 'Community-Consensus TI 
ComposiLINK HERE te. (https://spot.colorado.edu/~koppg/T
 *  Units:nits <sup> :  </sup>W m-2s

#Include an embedded image to explain the concept to an user. Configure settings for high resolution images
#Include citations!!!

#Each firgure must be immediately followed by a Markdown cell with figure caption

#A final markdown cell contains the summary of results and conclusions

### This should take he form of a function through which arguments can be passed, which then returs a value of T (temperature)

### Analyze and create effective visualizations of the results from “single forcing” experiments from the NASA GISS ModelE2 climate model. Based on this analysis, create a well-communicated narrative to describe how and why each “forcing agent” impacts the terms in your energy balance equation derived above

1). What is “total solar irradiance” (TSI) a measure of?

2.) The “Solar Constant, S0” is approximated as constant in our energy budget 
calculations, however observational records do indicate that it varies in time. 
From 1610 to 2018, what is the mean and the magnitude of the interannualvariability?

3.) Create an effective visualization of the Total Solar Irradiance (TSI) record. You 
must create a figure caption in the markdown cell immediately below.

4.) In a near-by cell, explain to a reader what drives these relatively short-term
variations in solar activity. You must cite your sources.

5.) The Maunder Minimum was a period of extremely low solar activity in from ~1650 
to 1715. How much would Earth’s global average surface air temperature have 
dropped during this period (still ignoring greenhouse gases in our model and 
assuming constant albedo)

6.) Using the observational record of TSI, calculate Tearth (the global average
temperature of Earth) assuming albedo and emissivity are constant. Create a 
single figure with two subpanels with an effective visualization of these two 
metrics together. You must create a figure caption in the markdown cell 
immediately below

7.) Create a table using markdown that displays the mean + std for both the total 
irradiance and Tearth over this period. Relative to Earth’s average global mean 
surface temperature, what % does this variability amount to?

8.) Use your model to teach someone about the role of albedo in Earth’s climate 
system (assume emissivity and S0 are constant). What happens if albedo were to 
increase or decrease and why? What processes would potentially drive an 
increase or decrease in planetary albedo?

9.) Use your model to teach someone about the emissivity parameter in the energy 
budget equation (assume albedo and S0 are constant). What happens if emissivity 
were to increase or decrease and why? What processes would potentially drive an 
increase or decreased in planetary emissivity?

10.) Using the simulation results from the NASA GISS ModelE2 single forcing
experiments, create an effective visualization (or visualizations) of how Earth’s 
global average surface air temperature changes in response to each forcing agent.
You must create a figure caption in the markdown cell immediately below.

11.) Read the following article (which uses a different model!) : 
https://www.carbonbrief.org/analysis-why-scientists-think-100-of-global-warmingis-due-to-humans/ and then go back to your analysis and use your model results to 
teach a reader:
a. How each forcing agent influences Earth’s temperature and why (you need 
to show scientific understanding).
b. Evidence of why we are confident that the observed warming is the result 
of anthropogenic influence.

In [1]:
# import our packages
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
#Import datasets

#Define homw working directory
ees_climate_dir = 'C:/Users/TU_Climate24_Student/Desktop/ees_climate/'  #### This is the home directory we are always working out of

temp_NASA = pd.read_csv(ees_climate_dir+'unit2_grisales/data/model_results/NASA_GISS_Response_To_Forcings.csv')#,parse_dates=['Date'])
temp_observed = pd.read_csv(ees_climate_dir+'unit2_grisales/data/model_results/Observed_Temps.csv')#,parse_dates=['Date'])
solar_constant_data = pd.read_csv("https://spot.colorado.edu/~koppg/TSI/Historical_TSI_Reconstruction.txt", 
                                  skiprows=6, sep=' ').rename(columns={';':'year', 'Year':'NaN', 'Unnamed: 2':'NaN2',
                                                                       'Unnamed: 3':'NaN3', 'TSI':'NaN4',
                                                                       '[W/m^2]':'TSI [W/m^2]'})

Display the first five rows of each dataset to explore their structure

In [3]:
temp_NASA.head(5)

,Year,All forcings,Human,Natural,Anthropogenic tropospheric aerosol,Greenhouse gases,Land use,Orbital changes,Ozone,Solar,Volcanic
0,1850,287.467659,287.428996,287.446649,287.425891,287.417000,287.450350,287.442937,287.450645,287.450350,287.446649
1,1851,287.517853,287.433725,287.460201,287.446402,287.399260,287.394453,287.450825,287.407646,287.434744,287.458259
2,1852,287.517558,287.473824,287.530642,287.498657,287.415606,287.482750,287.453118,287.447467,287.466309,287.560542
3,1853,287.478262,287.454695,287.519732,287.417325,287.433217,287.509894,287.468205,287.475366,287.455296,287.534299
4,1854,287.477572,287.417804,287.507810,287.424542,287.420589,287.445774,287.486590,287.454192,287.436233,287.552440

In [4]:
temp_observed.head(5)

   Year  Annual_Mean  5-year_Mean
0  1880        -0.23          NaN
1  1881        -0.15          NaN
2  1882        -0.18        -0.21
3  1883        -0.21        -0.22
4  1884        -0.29        -0.24

In [5]:
solar_constant_data.head(5)

     year  NaN  NaN2  NaN3  NaN4  TSI [W/m^2]
0  1610.5  NaN   NaN   NaN   NaN    1360.1856
1  1611.5  NaN   NaN   NaN   NaN    1360.4700
2  1612.5  NaN   NaN   NaN   NaN    1360.6798
3  1613.5  NaN   NaN   NaN   NaN    1360.9569
4  1614.5  NaN   NaN   NaN   NaN    1361.0877

# Define the variables needed to estimate the Earth's surface temperature

In [6]:
earth_rad =  6378137              # Earth's radius in meters
sun_rad = 696000000               # Sun's radius in meters
d_earth =  149600000000           # Distance of the Earth from the Sun in meters
sigma = 5.67e-8                   # Stefan-Boltzman constant W⋅m−2⋅K−4
epsilon = 1                       # Emissivity for a blackbody - unitliess
T_sun =  5778                     # Sun's average surface temperature in Kelvin

## Absorbed shortwave radiation (ASR)

$$
Energy_{in} = (1 - \alpha)S_{0}\pi R_{earth}^2
$$

In [7]:
energy_flux_sun = epsilon * sigma * (T_sun)**4
Q_sun = energy_flux_sun * (4 * np.pi * (sun_rad ** 2))
S_constant = Q_sun / (4 * np.pi * (d_earth ** 2))
Esun_incident = S_constant*(np.pi*earth_rad**2)
alpha = 0.3

In [8]:
Energy_in = Esun_incident - alpha * S_constant * np.pi * (earth_rad **2)
Energy_in

1.223725755897003e+17

## Earths surface temperature (T$_{earth}$):

$$
T_{earth} = \sqrt[4]{\frac{(1 - \alpha) S_{0}}{4 \epsilon \sigma}}
$$

In [12]:
T_earth = ( ((1- alpha)*S_constant)/(4*epsilon*sigma) ) ** 0.25
T_earth

254.90354346227977

# Scenarios

Changes in albedo ($ \alpha$)

Changes in $ S_{0} $ and therefore in ASR

Changes in atmospheric emissivity ($ \epsilon $)

In [21]:
def earth_surface_temp(albedo = 0.3,S0 = S_constant, emissivity = epsilon):
    """ 
    This function estimates the Earth's surface temperature using a simple
    energy balance model of the Earth System.
    
    Parameters
    ----------
    input : albedo (float)
    input : S0 (float)
    input : emissivity (float)
    
    Returns
    -------
    output: temp_earth (float)
    
    """
    #energy_flux_sun = epsilon * sigma * (T_sun)**4
    #Q_sun = energy_flux_sun * (4 * np.pi * (sun_rad ** 2))
    #S_constant = Q_sun / (4 * np.pi * (d_earth ** 2))
    Esun_incident = S0*(np.pi*earth_rad**2)
    Energy_in = Esun_incident - albedo * S0 * np.pi * (earth_rad **2)
    temp_earth = ( ((1- albedo)*S0)/(4*emissivity*sigma) ) ** 0.25
    
    return temp_earth, temp_earth-272.15

In [22]:
earth_surface_temp()

(254.90354346227977, -17.246456537720206)

In [23]:
earth_surface_temp(albedo = 1)

(0.0, -272.15)

In [24]:
earth_surface_temp(albedo = 0)

(278.6771514842189, 6.527151484218905)

In [26]:
seq_alpha = np.arange(0,1,0.1) #Creates a sequence with alpha values ranging from 0 to 1 by 0.1
seq_alpha

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [29]:
earth_surface_temp(albedo = seq_alpha)

(array([278.67715148, 271.43258959, 263.55657764, 254.90354346,
        245.2670318 , 234.3386177 , 221.62378135, 206.24416782,
        186.36264327, 156.71167867]),
 array([   6.52715148,   -0.71741041,   -8.59342236,  -17.24645654,
         -26.8829682 ,  -37.8113823 ,  -50.52621865,  -65.90583218,
         -85.78735673, -115.43832133]))

In [39]:
earth_surface_temp(S0 = solar_constant_data['TSI [W/m^2]'])

(0      254.544250
 1      254.557554
 2      254.567368
 3      254.580327
 4      254.586444
           ...
 404    254.609845
 405    254.615151
 406    254.598166
 407    254.592382
 408    254.594313
 Name: TSI [W/m^2], Length: 409, dtype: float64,
 0     -17.605750
 1     -17.592446
 2     -17.582632
 3     -17.569673
 4     -17.563556
          ...
 404   -17.540155
 405   -17.534849
 406   -17.551834
 407   -17.557618
 408   -17.555687
 Name: TSI [W/m^2], Length: 409, dtype: float64)

In [41]:
seq_epsilon = np.arange(0,1,0.1) #Creates a sequence with epsilon values ranging from 0 to 1 by 0.1
seq_epsilon

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [42]:
earth_surface_temp(emissivity = seq_epsilon)

C:\Users\TU_Climate24_Student\AppData\Local\Temp\ipykernel_6900\2607043942.py:22: RuntimeWarning: divide by zero encountered in divide
  temp_earth = ( ((1- albedo)*S0)/(4*emissivity*sigma) ) ** 0.25

(array([         inf, 453.28972288, 381.16970305, 344.42570739,
        320.52423689, 303.13310752, 289.62634266, 278.67715148,
        269.52768181, 261.70694353]),
 array([         inf, 181.13972288, 109.01970305,  72.27570739,
         48.37423689,  30.98310752,  17.47634266,   6.52715148,
         -2.62231819, -10.44305647]))

In [45]:
print(solar_constant_data['TSI [W/m^2]'].mean(),solar_constant_data['TSI [W/m^2]'].min(),solar_constant_data['TSI [W/m^2]'].max())

1360.9803982885085 1360.1856 1362.3628

In [48]:
seq_S0 = np.arange(0,10000,500) #Creates a sequence with alpha values ranging from 0 to 1 by 0.1
seq_S0

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000,
       5500, 6000, 6500, 7000, 7500, 8000, 8500, 9000, 9500])

In [49]:
earth_surface_temp(S0 = seq_S0)

(array([  0.        , 198.20118583, 235.7022604 , 260.84743001,
        280.29880508, 296.37990167, 310.2016197 , 322.38940338,
        333.33333333, 343.29452398, 352.45708781, 360.95612844,
        368.89397323, 376.35014406, 383.3877723 , 390.05788655,
        396.40237167, 402.45606713, 408.24829046, 413.80396603]),
 array([-272.15      ,  -73.94881417,  -36.4477396 ,  -11.30256999,
           8.14880508,   24.22990167,   38.0516197 ,   50.23940338,
          61.18333333,   71.14452398,   80.30708781,   88.80612844,
          96.74397323,  104.20014406,  111.2377723 ,  117.90788655,
         124.25237167,  130.30606713,  136.09829046,  141.65396603]))